### ISSUE TITLE
Question on heldout method to estimate K

### ISSUE THREAD

**Issue by WuyangFF95** [lrgr/tcsm#11]
Dear @wir963,

I understood the way you did heldout method to estimate the best K. For each K, you split all the tumors into two parts - train dataset (80%) and test dataset (20%), and you can estimate the likelihood for each specific value of K.

Now the question is, do I need to do the heldout 5 times for each K to calculate 5 different likelihood values? Or I only need to do once?

**Comment by WuyangFF95** [comment]
Dear @wir963 ,

Another question is that, in your paper you said 

> "We choose the K when the likelihood plateaus"

But how did you define "plateaus"? Do you mean (1) likelihood stops increasing? (2) likelihood starts decreasing? (3) increment of likelihood is smaller than a value? (4) The second derivative of likelihood against K starts decreasing?

I did one tcsm run using my own data where I know the ground-truth K should be 2. However, the likelihood slightly increases when K increases from 2 to 10:

>         2         3         4         5         6         7         8         9 
> -4.179222 -4.178338 -4.178184 -4.178126 -4.178055 -4.178020 -4.177986 -4.177956 
>        10 
> -4.177929

If you pick K based on (1) or (2), then I would pick K = 10; if K is picked based on (4), then I would pick K = 3. What should I do then? Thanks!

**Comment by wir963** [comment]
Hey @WuyangFF95 

Sorry for the late response. One weakness of our method is our method for model selection is a little hand-wavy because "plateau" is subject to interpretation. This was one area where I was looking forward to improving for future research but then my research focus shifted. I used (3) but I don't have a defined value (I just looked at the plot). 

For the earlier question, we did 5-fold cross validation so we take the mean likelihood for all five held-out likelihoods for a given K (I know it can take a while, sorry...)

**Comment by WuyangFF95** [comment]
Can you provide an defined value if you choose K which makes increment of likelihood is smaller than a value?

The speed is not an issue. I did 5-fold cross-validation, and I still found your program runs very fast.

**Comment by wir963** [comment]
Hmmm I'll discuss with the corresponding author on the paper @mdml and we'll let you know

**Comment by wir963** [comment]
@WuyangFF95 - sorry for the delay. @mdml and I both think that either if the likelihood per mutation changes by less than one-hundredth or the second derivative of likelihood against K starts decreasing make sense.

**Comment by WuyangFF95** [comment]
Thank you @wir963 ! I will try "increment of likelihood per change of K < 0.01".

**Comment by WuyangFF95** [comment]
Sorry for the typo.

I didn't mean 

> the second derivative of likelihood against K starts decreasing

Instead, I would like to find the K where the second derivative of likelihood against K drops from positive to zero or negative. i.e. The likelihood against K starts to decrease, or increases more slowly against K.
